# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

container:
  image: alpine:latest
  env:
    RELEASE_MAJOR: $(Date:yyyyMMdd)
    RELEASE_MINOR: $(Rev:r)
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
steps:
- task: Docker@2
  displayName: Build
  inputs:
    command: build
    tags: tag1
    arguments: --secret id=mysecret,src=mysecret.txt
