name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    #runs-on: self-hosted
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello from ARC runner!"
        
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          platforms: linux/amd64,linux/arm64
          push: false
          tags: user/app:latest
          driver: remote
          endpoint: tcp://localhost:1234
